export const scottishCouncils = [
  {
    councilName: 'Aberdeen City Council',
    councilArea: 'Aberdeen City',
    websiteUrl: 'https://www.aberdeencity.gov.uk',
    landlordRegUrl: 'https://www.aberdeencity.gov.uk/services/housing/landlord-registration',
    hmoLicenseUrl: 'https://www.aberdeencity.gov.uk/services/housing/hmo-licensing',
    registrationFee: 88,
    renewalFee: 88,
    hmoFee: 1095,
    processingTimeDays: 28,
    contactEmail: 'landlordregistration@aberdeencity.gov.uk',
    contactPhone: '03000 200 292',
  },
  {
    councilName: 'Aberdeenshire Council',
    councilArea: 'Aberdeenshire',
    websiteUrl: 'https://www.aberdeenshire.gov.uk',
    landlordRegUrl: 'https://www.aberdeenshire.gov.uk/housing/landlord-registration',
    hmoLicenseUrl: 'https://www.aberdeenshire.gov.uk/housing/hmo',
    registrationFee: 77,
    renewalFee: 77,
    hmoFee: 890,
    processingTimeDays: 21,
    contactEmail: 'landlord.registration@aberdeenshire.gov.uk',
    contactPhone: '0345 608 1208',
  },
  {
    councilName: 'Angus Council',
    councilArea: 'Angus',
    websiteUrl: 'https://www.angus.gov.uk',
    landlordRegUrl: 'https://www.angus.gov.uk/housing/landlord_registration',
    hmoLicenseUrl: 'https://www.angus.gov.uk/housing/hmo_licensing',
    registrationFee: 88,
    renewalFee: 88,
    hmoFee: 995,
    processingTimeDays: 28,
    contactEmail: 'landlordregistration@angus.gov.uk',
    contactPhone: '03452 777 778',
  },
  {
    councilName: 'Argyll and Bute Council',
    councilArea: 'Argyll and Bute',
    websiteUrl: 'https://www.argyll-bute.gov.uk',
    landlordRegUrl: 'https://www.argyll-bute.gov.uk/housing/landlord-registration',
    hmoLicenseUrl: 'https://www.argyll-bute.gov.uk/housing/hmo',
    registrationFee: 88,
    renewalFee: 88,
    hmoFee: 950,
    processingTimeDays: 28,
    contactEmail: 'landlordregistration@argyll-bute.gov.uk',
    contactPhone: '01546 605514',
  },
  {
    councilName: 'City of Edinburgh Council',
    councilArea: 'Edinburgh',
    websiteUrl: 'https://www.edinburgh.gov.uk',
    landlordRegUrl: 'https://www.edinburgh.gov.uk/landlord-registration',
    hmoLicenseUrl: 'https://www.edinburgh.gov.uk/hmo',
    registrationFee: 88,
    renewalFee: 88,
    hmoFee: 1845,
    processingTimeDays: 42,
    contactEmail: 'landlord.registration@edinburgh.gov.uk',
    contactPhone: '0131 529 7454',
  },
  {
    councilName: 'Clackmannanshire Council',
    councilArea: 'Clackmannanshire',
    websiteUrl: 'https://www.clacks.gov.uk',
    landlordRegUrl: 'https://www.clacks.gov.uk/housing/landlordregistration',
    hmoLicenseUrl: 'https://www.clacks.gov.uk/housing/hmo',
    registrationFee: 88,
    renewalFee: 88,
    hmoFee: 850,
    processingTimeDays: 21,
    contactEmail: 'landlordregistration@clacks.gov.uk',
    contactPhone: '01259 450000',
  },
  {
    councilName: 'Dumfries and Galloway Council',
    websiteUrl: 'https://www.dumgal.gov.uk',
    landlordRegUrl: 'https://www.dumgal.gov.uk/article/15274/Landlord-Registration',
    hmoLicenseUrl: 'https://www.dumgal.gov.uk/article/17621/HMO-Licensing',
    registrationFee: 88,
    renewalFee: 88,
    hmoFee: 920,
    processingTimeDays: 28,
    contactEmail: 'landlord.registration@dumgal.gov.uk',
    contactPhone: '030 33 33 3000',
  },
  {
    councilName: 'Dundee City Council',
    websiteUrl: 'https://www.dundeecity.gov.uk',
    landlordRegUrl: 'https://www.dundeecity.gov.uk/landlord-registration',
    hmoLicenseUrl: 'https://www.dundeecity.gov.uk/hmo-licensing',
    registrationFee: 88,
    renewalFee: 88,
    hmoFee: 1245,
    processingTimeDays: 35,
    contactEmail: 'landlordregistration@dundeecity.gov.uk',
    contactPhone: '01382 434000',
  },
  {
    councilName: 'East Ayrshire Council',
    websiteUrl: 'https://www.east-ayrshire.gov.uk',
    landlordRegUrl: 'https://www.east-ayrshire.gov.uk/Housing/Landlord-Registration',
    hmoLicenseUrl: 'https://www.east-ayrshire.gov.uk/Housing/HMO',
    registrationFee: 88,
    renewalFee: 88,
    hmoFee: 880,
    processingTimeDays: 28,
    contactEmail: 'landlordregistration@east-ayrshire.gov.uk',
    contactPhone: '01563 576000',
  },
  {
    councilName: 'East Dunbartonshire Council',
    websiteUrl: 'https://www.eastdunbarton.gov.uk',
    landlordRegUrl: 'https://www.eastdunbarton.gov.uk/landlord-registration',
    hmoLicenseUrl: 'https://www.eastdunbarton.gov.uk/hmo',
    registrationFee: 88,
    renewalFee: 88,
    hmoFee: 1150,
    processingTimeDays: 28,
    contactEmail: 'landlordregistration@eastdunbarton.gov.uk',
    contactPhone: '0300 123 4510',
  },
  {
    councilName: 'East Lothian Council',
    websiteUrl: 'https://www.eastlothian.gov.uk',
    landlordRegUrl: 'https://www.eastlothian.gov.uk/landlord-registration',
    hmoLicenseUrl: 'https://www.eastlothian.gov.uk/hmo',
    registrationFee: 88,
    renewalFee: 88,
    hmoFee: 995,
    processingTimeDays: 28,
    contactEmail: 'landlordregistration@eastlothian.gov.uk',
    contactPhone: '01620 827827',
  },
  {
    councilName: 'East Renfrewshire Council',
    websiteUrl: 'https://www.eastrenfrewshire.gov.uk',
    landlordRegUrl: 'https://www.eastrenfrewshire.gov.uk/landlord-registration',
    hmoLicenseUrl: 'https://www.eastrenfrewshire.gov.uk/hmo',
    registrationFee: 88,
    renewalFee: 88,
    hmoFee: 1050,
    processingTimeDays: 28,
    contactEmail: 'landlordregistration@eastrenfrewshire.gov.uk',
    contactPhone: '0141 577 3000',
  },
  {
    councilName: 'Falkirk Council',
    websiteUrl: 'https://www.falkirk.gov.uk',
    landlordRegUrl: 'https://www.falkirk.gov.uk/services/homes-property/landlord-registration',
    hmoLicenseUrl: 'https://www.falkirk.gov.uk/services/homes-property/hmo',
    registrationFee: 88,
    renewalFee: 88,
    hmoFee: 1100,
    processingTimeDays: 28,
    contactEmail: 'landlordregistration@falkirk.gov.uk',
    contactPhone: '01324 506070',
  },
  {
    councilName: 'Fife Council',
    websiteUrl: 'https://www.fife.gov.uk',
    landlordRegUrl: 'https://www.fife.gov.uk/landlord-registration',
    hmoLicenseUrl: 'https://www.fife.gov.uk/hmo',
    registrationFee: 88,
    renewalFee: 88,
    hmoFee: 1295,
    processingTimeDays: 35,
    contactEmail: 'landlordregistration@fife.gov.uk',
    contactPhone: '03451 55 00 22',
  },
  {
    councilName: 'Glasgow City Council',
    websiteUrl: 'https://www.glasgow.gov.uk',
    landlordRegUrl: 'https://www.glasgow.gov.uk/landlordregistration',
    hmoLicenseUrl: 'https://www.glasgow.gov.uk/hmo',
    registrationFee: 88,
    renewalFee: 88,
    hmoFee: 2100,
    processingTimeDays: 56,
    contactEmail: 'landlordregistration@glasgow.gov.uk',
    contactPhone: '0141 287 2000',
  },
  {
    councilName: 'Highland Council',
    websiteUrl: 'https://www.highland.gov.uk',
    landlordRegUrl: 'https://www.highland.gov.uk/landlord-registration',
    hmoLicenseUrl: 'https://www.highland.gov.uk/hmo',
    registrationFee: 88,
    renewalFee: 88,
    hmoFee: 975,
    processingTimeDays: 28,
    contactEmail: 'landlordregistration@highland.gov.uk',
    contactPhone: '01349 886606',
  },
  {
    councilName: 'Inverclyde Council',
    websiteUrl: 'https://www.inverclyde.gov.uk',
    landlordRegUrl: 'https://www.inverclyde.gov.uk/housing/landlord-registration',
    hmoLicenseUrl: 'https://www.inverclyde.gov.uk/housing/hmo',
    registrationFee: 88,
    renewalFee: 88,
    hmoFee: 950,
    processingTimeDays: 28,
    contactEmail: 'landlordregistration@inverclyde.gov.uk',
    contactPhone: '01475 717171',
  },
  {
    councilName: 'Midlothian Council',
    websiteUrl: 'https://www.midlothian.gov.uk',
    landlordRegUrl: 'https://www.midlothian.gov.uk/landlord-registration',
    hmoLicenseUrl: 'https://www.midlothian.gov.uk/hmo',
    registrationFee: 88,
    renewalFee: 88,
    hmoFee: 1050,
    processingTimeDays: 28,
    contactEmail: 'landlordregistration@midlothian.gov.uk',
    contactPhone: '0131 270 7500',
  },
  {
    councilName: 'Moray Council',
    websiteUrl: 'https://www.moray.gov.uk',
    landlordRegUrl: 'https://www.moray.gov.uk/landlord-registration',
    hmoLicenseUrl: 'https://www.moray.gov.uk/hmo',
    registrationFee: 88,
    renewalFee: 88,
    hmoFee: 890,
    processingTimeDays: 28,
    contactEmail: 'landlordregistration@moray.gov.uk',
    contactPhone: '01343 543451',
  },
  {
    councilName: 'Na h-Eileanan Siar Council',
    websiteUrl: 'https://www.cne-siar.gov.uk',
    landlordRegUrl: 'https://www.cne-siar.gov.uk/landlord-registration',
    hmoLicenseUrl: 'https://www.cne-siar.gov.uk/hmo',
    registrationFee: 88,
    renewalFee: 88,
    hmoFee: 750,
    processingTimeDays: 21,
    contactEmail: 'landlordregistration@cne-siar.gov.uk',
    contactPhone: '01851 703773',
  },
  {
    councilName: 'North Ayrshire Council',
    websiteUrl: 'https://www.north-ayrshire.gov.uk',
    landlordRegUrl: 'https://www.north-ayrshire.gov.uk/landlord-registration',
    hmoLicenseUrl: 'https://www.north-ayrshire.gov.uk/hmo',
    registrationFee: 88,
    renewalFee: 88,
    hmoFee: 1020,
    processingTimeDays: 28,
    contactEmail: 'landlordregistration@north-ayrshire.gov.uk',
    contactPhone: '01294 310000',
  },
  {
    councilName: 'North Lanarkshire Council',
    websiteUrl: 'https://www.northlanarkshire.gov.uk',
    landlordRegUrl: 'https://www.northlanarkshire.gov.uk/landlord-registration',
    hmoLicenseUrl: 'https://www.northlanarkshire.gov.uk/hmo',
    registrationFee: 88,
    renewalFee: 88,
    hmoFee: 1450,
    processingTimeDays: 35,
    contactEmail: 'landlordregistration@northlan.gov.uk',
    contactPhone: '01698 403110',
  },
  {
    councilName: 'Orkney Islands Council',
    websiteUrl: 'https://www.orkney.gov.uk',
    landlordRegUrl: 'https://www.orkney.gov.uk/landlord-registration',
    hmoLicenseUrl: 'https://www.orkney.gov.uk/hmo',
    registrationFee: 88,
    renewalFee: 88,
    hmoFee: 650,
    processingTimeDays: 21,
    contactEmail: 'landlordregistration@orkney.gov.uk',
    contactPhone: '01856 873535',
  },
  {
    councilName: 'Perth and Kinross Council',
    websiteUrl: 'https://www.pkc.gov.uk',
    landlordRegUrl: 'https://www.pkc.gov.uk/landlordregistration',
    hmoLicenseUrl: 'https://www.pkc.gov.uk/hmo',
    registrationFee: 88,
    renewalFee: 88,
    hmoFee: 1175,
    processingTimeDays: 28,
    contactEmail: 'landlordregistration@pkc.gov.uk',
    contactPhone: '01738 475000',
  },
  {
    councilName: 'Renfrewshire Council',
    websiteUrl: 'https://www.renfrewshire.gov.uk',
    landlordRegUrl: 'https://www.renfrewshire.gov.uk/landlord-registration',
    hmoLicenseUrl: 'https://www.renfrewshire.gov.uk/hmo',
    registrationFee: 88,
    renewalFee: 88,
    hmoFee: 1295,
    processingTimeDays: 28,
    contactEmail: 'landlordregistration@renfrewshire.gov.uk',
    contactPhone: '0300 300 0300',
  },
  {
    councilName: 'Scottish Borders Council',
    websiteUrl: 'https://www.scotborders.gov.uk',
    landlordRegUrl: 'https://www.scotborders.gov.uk/landlord-registration',
    hmoLicenseUrl: 'https://www.scotborders.gov.uk/hmo',
    registrationFee: 88,
    renewalFee: 88,
    hmoFee: 890,
    processingTimeDays: 28,
    contactEmail: 'landlordregistration@scotborders.gov.uk',
    contactPhone: '0300 100 1800',
  },
  {
    councilName: 'Shetland Islands Council',
    websiteUrl: 'https://www.shetland.gov.uk',
    landlordRegUrl: 'https://www.shetland.gov.uk/landlord-registration',
    hmoLicenseUrl: 'https://www.shetland.gov.uk/hmo',
    registrationFee: 88,
    renewalFee: 88,
    hmoFee: 700,
    processingTimeDays: 21,
    contactEmail: 'landlordregistration@shetland.gov.uk',
    contactPhone: '01595 744868',
  },
  {
    councilName: 'South Ayrshire Council',
    websiteUrl: 'https://www.south-ayrshire.gov.uk',
    landlordRegUrl: 'https://www.south-ayrshire.gov.uk/landlord-registration',
    hmoLicenseUrl: 'https://www.south-ayrshire.gov.uk/hmo',
    registrationFee: 88,
    renewalFee: 88,
    hmoFee: 950,
    processingTimeDays: 28,
    contactEmail: 'landlordregistration@south-ayrshire.gov.uk',
    contactPhone: '0300 123 0900',
  },
  {
    councilName: 'South Lanarkshire Council',
    websiteUrl: 'https://www.southlanarkshire.gov.uk',
    landlordRegUrl: 'https://www.southlanarkshire.gov.uk/landlord-registration',
    hmoLicenseUrl: 'https://www.southlanarkshire.gov.uk/hmo',
    registrationFee: 88,
    renewalFee: 88,
    hmoFee: 1395,
    processingTimeDays: 35,
    contactEmail: 'landlordregistration@southlanarkshire.gov.uk',
    contactPhone: '0303 123 1015',
  },
  {
    councilName: 'Stirling Council',
    websiteUrl: 'https://www.stirling.gov.uk',
    landlordRegUrl: 'https://www.stirling.gov.uk/landlord-registration',
    hmoLicenseUrl: 'https://www.stirling.gov.uk/hmo',
    registrationFee: 88,
    renewalFee: 88,
    hmoFee: 1050,
    processingTimeDays: 28,
    contactEmail: 'landlordregistration@stirling.gov.uk',
    contactPhone: '01786 404040',
  },
  {
    councilName: 'West Dunbartonshire Council',
    websiteUrl: 'https://www.west-dunbarton.gov.uk',
    landlordRegUrl: 'https://www.west-dunbarton.gov.uk/landlord-registration',
    hmoLicenseUrl: 'https://www.west-dunbarton.gov.uk/hmo',
    registrationFee: 88,
    renewalFee: 88,
    hmoFee: 1050,
    processingTimeDays: 28,
    contactEmail: 'landlordregistration@west-dunbarton.gov.uk',
    contactPhone: '01389 737000',
  },
  {
    councilName: 'West Lothian Council',
    websiteUrl: 'https://www.westlothian.gov.uk',
    landlordRegUrl: 'https://www.westlothian.gov.uk/landlord-registration',
    hmoLicenseUrl: 'https://www.westlothian.gov.uk/hmo',
    registrationFee: 88,
    renewalFee: 88,
    hmoFee: 1175,
    processingTimeDays: 28,
    contactEmail: 'landlordregistration@westlothian.gov.uk',
    contactPhone: '01506 280000',
  },
]
